name: Export Dynamic Plugin Packages
on:
  workflow_call:
    inputs:
      node-version:
        description: node-version to execute the export
        type: string
        required: false
        default: "18.x"
      janus-cli-version:
        description: Version of the janus-idp/cli package.
        type: string
        required: false
        default: "^1.8.5"

      plugins-repo:
        description:
          Name of the repository that contains the backstage plugins to be exported as dynamic. For example
          backstage/backstage.
        type: string
        required: true
      plugins-repo-ref:
        description:
          Git ref (tag, branch or SHA) of the repository that contains the backstage plugins to be exported as dynamic.
          For example backstage/backstage.
        type: string
        required: true
      plugins-root:
        description:
          Monorepo root relative folder, in the repository that contains the backstage plugins to be exported as
          dynamic.
        required: false
        type: string
        default: ""

      overlay-repo:
        description:
          Name of the repository that contains the list of backstage plugins to be exported as dynamic, as well as
          optional export directives and source overlays.
        required: true
        type: string
      overlay-repo-ref:
        description:
          Git ref (tag, branch or SHA) of the repository that contains the list of backstage plugins to be exported as
          dynamic, as well as optional export directives and source overlays.
        type: string
        required: true

      publish-container:
        description: Flag to either publish a container image with the dynamic plugin or not
        type: boolean
        default: false
        required: false

      publish-release-assets:
        description:
          Whether the dynamic plugin archives should be published as GitHub release assets or pushed as workflow
          artifacts.
        required: false
        type: boolean
        default: ${{ github.ref_type == 'tag' && github.event_name == 'push' }}

      artifact-retention-days:
        description:
          Number of days the dynamic plugin archives will be kept as a workflow artifact (if not published as release
          assets).
        required: false
        type: number
        default: 1

      upload-project-on-error:
        description: Upload the complete project as a workflow artifact in case of error in order to troubleshoot.
        required: false
        type: boolean
        default: false

jobs:
  export:
    runs-on: ubuntu-latest

    env:
      NODE_OPTIONS: --max-old-space-size=8192
      IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
    name: Export
    steps:

      - name: Checkout plugins repository ${{ inputs.plugins-repo }}
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        if: ${{ inputs.plugins-root == '' }}
        with:
          repository: ${{ inputs.plugins-repo }}
          ref: ${{ inputs.plugins-repo-ref }}

      - name: Checkout plugins repository ${{ inputs.plugins-repo }} at ${{ inputs.plugins-root }}
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        if: ${{ inputs.plugins-root != '' }}
        with:
          repository: ${{ inputs.plugins-repo }}
          ref: ${{ inputs.plugins-repo-ref }}
          sparse-checkout: |
            .yarn
            .yarnrc.yml
            ${{ inputs.plugins-root }}
          sparse-checkout-cone-mode: false

      # This step is needed because some github actions below do not support paths.
      # Therefore the plugins-root assets should be moved to the project root.
      - name: Move the plugin-root files to the project root
        if: ${{ inputs.plugins-root != '' }}
        run: |
          echo "  project root files before the move:"
          ls -lah
          echo "  copy plugins-root files to the project root"
          cp -rT ${{ inputs.plugins-root}} $(pwd)
          echo "  remove all plugins-root files"
          rm -rf ${{ inputs.plugins-root}}
          echo "  project root files after the move:"
          ls -lah

      - name: Checkout overlay repository ${{ inputs.overlay-repo }} in the 'overlay-repo' sub-folder
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: ${{ inputs.overlay-repo }}
          ref: ${{ inputs.overlay-repo-ref }}
          path: overlay-repo

      - name: Use node.js ${{ inputs.node-version }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: https://registry.npmjs.org/ # Needed for auth

      - name: Run yarn install
        uses: backstage/actions/yarn-install@a674369920067381b450d398b27df7039b7ef635 # v0.6.5
        with:
          cache-prefix: ${{ runner.os }}-v${{ inputs.node-version }}

      - name: Run Typescript type checking
        run: yarn tsc

      - name: Install Podman
        if: ${{ inputs.publish-container }}
        uses: gacts/install-podman@v1.1.1

      - name: Set Plugin Base Image Name
        id: set-image-tag-name
        shell: bash
        run: |
          BASE_IMAGE_TAG_NAME=""
          if [[ "${{ inputs.publish-container  }}" ]]
          then
            BASE_IMAGE_TAG_NAME="${env.IMAGE_REGISTRY}/${{ inputs.image-tag-name }})"
          else
            echo "Not publish container image with plugin content"
          fi
          echo "BASE_IMAGE_TAG_NAME=$BASE_IMAGE_TAG_NAME" >> $GITHUB_OUTPUT

      - name: Export dynamic plugin packages
        if: ${{ success() }}
        id: export-dynamic
        uses: redhat-developer/rhdh-plugin-export-utils/export-dynamic@main
        with:
          plugins-file: ${{ github.workspace }}/overlay-repo/${{inputs.plugins-root}}/plugins-list.yaml
          destination: ${{ github.workspace }}/dynamic-plugin-archives
          janus-cli-version: ${{inputs.janus-cli-version}}
          base-image-tag-name: ${{ steps.set-image-tag-name.outputs.BASE_IMAGE_TAG_NAME }}

      - name: Set artifacts name suffix
        id: set-artifacts-name-suffix
        shell: bash
        run: |
          ARTIFACTS_NAME_SUFFIX=""
          if [[ "${{  inputs.plugins-root }}" != "" ]]
          then
            ARTIFACTS_NAME_SUFFIX=" ($(echo '${{  inputs.plugins-root }}' | sed -e 's:/:-:g'))"
          fi
          echo "ARTIFACTS_NAME_SUFFIX=$ARTIFACTS_NAME_SUFFIX" >> $GITHUB_OUTPUT

      - name: Upload exported archives to workflow artifacts
        uses: actions/upload-artifact@v4
        if: ${{ !inputs.publish-release-assets && success() }}
        with:
          name: dynamic plugin packages${{ steps.set-artifacts-name-suffix.outputs.ARTIFACTS_NAME_SUFFIX }}
          path: ${{ github.workspace }}/dynamic-plugin-archives
          if-no-files-found: warn
          retention-days: ${{ inputs.artifact-retention-days }}
          overwrite: true

      - name: Upload the project to workflow artifacts on failure
        uses: actions/upload-artifact@v4
        if: ${{ inputs.upload-project-on-error && (failure() || steps.export-dynamic.outputs.errors) }}
        with:
          name: project root folder${{ steps.set-artifacts-name-suffix.outputs.ARTIFACTS_NAME_SUFFIX }}
          path: |
            ${{ github.workspace }}
            !${{ github.workspace }}/dynamic-plugin-archives
            !${{ github.workspace }}/node_modules
          if-no-files-found: warn
          retention-days: ${{ inputs.artifact-retention-days }}
          overwrite: true

      - name: Check export errors
        if: ${{ success() && steps.export-dynamic.outputs.errors != '' }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('The export failed for the following plugins: \n' + '${{ steps.export-dynamic.outputs.ERRORS }}'.replace(/^(.*..*)$/gm, '- $1 (https://github.com/${{ inputs.plugins-repo }}/tree/${{ inputs.plugins-repo-ref}}/${{ inputs.plugins-root}}/$1)'))

      - name: Publish exported plugins as GitHub release assets
        uses: softprops/action-gh-release@v2
        if: ${{ success() && inputs.publish-release-assets }}
        with:
          body:
            Dynamic Plugins for Red Hat Developer Hub ${{ github.ref_name }}, exported from ${{ inputs.plugins-repo }}.
          files: ${{ github.workspace }}/dynamic-plugin-archives/*
          repository: ${{ github.repository }}
